spring.application.name=eureka-server
server.port=8761

# configuración modo servidor
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false

# logs para trazabilidad
logging.level.com.netflix.eureka=WARN